const express = require('express')
const app = express()
const mongoose = require('mongoose')
const session = require(express-session)
const MongoStore = require(connect-mongo)(session)
const connectDB = require(',/config/database')
require('dotenv').config({path: './config/.env'})